name: Deploy to Nekoweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Nekoweb
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build Eleventy
        run: npm run build

      - name: Deploy to Nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: minna.nekoweb.org
          nekoweb-username: minna
          directory: public
